name: Test workflow
on: [push]
jobs:
  test-job:
    name: Test job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered !!!"
      - run: echo "${{github.event_name}}"
      - run: echo "${{github.event}}"
